AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/OpenStructUse:
  Exclude:
    - 'spec/**/*'

Style/RedundantConstantBase:
  Exclude:
    - 'spec/**/*'

Style/ZeroLengthPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
